### ISSUE TITLE
Empty responses cause JS Error

### ISSUE THREAD

**Issue by moderndeveloperllc** [esphen/RESTED#90]
For 204 and 201 responses with no response body, you get the following JS error:
```
uncaught at f SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at o (chrome-extension://efhficcaphambolcidkajacbepebblnj/dist/rested.js:29:218793)
    at r.render (chrome-extension://efhficcaphambolcidkajacbepebblnj/dist/rested.js:29:1076673)
    at d._renderValidatedComponentWithoutOwnerOrContext (chrome-extension://efhficcaphambolcidkajacbepebblnj/dist/rested.js:29:1083106)
    at d._renderValidatedComponent (chrome-extension://efhficcaphambolcidkajacbepebblnj/dist/rested.js:29:1083318)
    at d._updateRenderedComponent (chrome-extension://efhficcaphambolcidkajacbepebblnj/dist/rested.js:29:1082537)
    at d._performComponentUpdate (chrome-extension://efhficcaphambolcidkajacbepebblnj/dist/rested.js:29:1082338)
    at d.updateComponent (chrome-extension://efhficcaphambolcidkajacbepebblnj/dist/rested.js:29:1081616)
    at d.receiveComponent (chrome-extension://efhficcaphambolcidkajacbepebblnj/dist/rested.js:29:1080733)
    at Object.receiveComponent (chrome-extension://efhficcaphambolcidkajacbepebblnj/dist/rested.js:6:185656)
f @ rested.js:6
(anonymous) @ rested.js:29
r @ rested.js:29
o @ rested.js:29
T @ rested.js:29
E @ rested.js:29
b @ rested.js:29
n @ rested.js:29
```

This also means that the cog keeps rotating forever and the response panel doesn't show.

**Comment by esphen** [comment]
Thanks for reporting! Assigning to the next bugfix milestone
